export const GET_LIST_PRODUCT = 'GET_LIST_PRODUCT';
export const GET_LIST_PRODUCT_SUCCESS = 'GET_LIST_PRODUCT_SUCCESS';

export const ON_ADD_PRODUCT = 'ON_ADD_PRODUCT';
export const ON_DELETE_PRODUCT = 'ON_DELETE_PRODUCT';

export const GET_DETAIL_PRODUCT = 'GET_DETAIL_PRODUCT';
export const GET_DETAIL_PRODUCT_SUCCESS = 'GET_DETAIL_PRODUCT_SUCCESS';

export const GET_LIST_ORDER_PRODUCT = 'GET_LIST_ORDER_PRODUCT';
export const GET_LIST_ORDER_SUCCESS = 'GET_LIST_ORDER_SUCCESS';

export const ON_BUY_PRODUCT = 'ON_BUY_PRODUCT';

export const ON_DELETE_ORDER_PRODUCT = 'ON_DELETE_ORDER_PRODUCT';

export const GET_LIST_ALL_ORDER_PRODUCT = 'GET_LIST_ALL_ORDER_PRODUCT';
export const GET_LIST_ALL_ORDER_SUCCESS = 'GET_LIST_ALL_ORDER_SUCCESS';

export const GET_LIST_CATEGORY = 'GET_LIST_CATEGORY';
export const GET_LIST_CATEGORY_SUCCESS = 'GET_LIST_CATEGORY_SUCCESS';