//customer
export const GET_LIST_CUSTOMERS = "GET_LIST_CUSTOMERS"
export const GET_LIST_CUSTOMERS_SUCCEESS = "GET_LIST_CUSTOMERS_SUCCEESS"

export const ON_ADD_CUSTOMERS = "ON_ADD_CUSTOMERS"

export const ON_DELETE_CUSTOMERS = "ON_DELETE_CUSTOMERS"
export const ON_DELETE_CUSTOMERS_SUCCESS = "ON_DELETE_CUSTOMERS_SUCCESS"


export const ON_UPDATE_CUSTOMERS = "ON_UPDATE_CUSTOMERS"

export const GET_DETAIL_CUSTOMERS = "GET_DETAIL_CUSTOMERS"
export const GET_DETAIL_CUSTOMERS_SUCCESS   = "GET_DETAIL_CUSTOMERS_SUCCESS"